# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
# source:
# - any: ['src/**/*', '!src/docs/*']

Core:
- 'src/App/**/*'
- 'src/Base/**/*'
- 'src/Gui/**/*'

:octocat::
- '.github/**/*'

Addon Manager:
- 'src/Mod/AddonManager/**/*'

WB Draft:
- 'src/Mod/Draft/**/*'

WB Mesh:
- 'src/Mod/Mesh/**/*'

WB MeshPart:
- 'src/Mod/MeshPart/**/*'

WB Part:  
- 'src/Mod/Part/**/*'

WB PartDesign:
- 'src/Mod/PartDesign/**/*'

WB Points:
- 'src/Mod/Points/**/*'

WB Sketcher:
- 'src/Mod/Sketcher/**/*'

WB Surface:
- 'src/Mod/Surface/**/*/'

WB TechDraw:
- 'src/Mod/TechDraw/**/*'

WB Test:
- 'src/Mod/Test/**/*'

